
chatgpt:
  token: sk-FSuizlbuyvLiYd6jF725B57cD6364e5c81C0F50409B50a00 #??
#  proxy-host: 127.0.0.1 #???????
#  proxy-port: 7890 #???????
#  model: text-davinci-003 #??
#  chat-model: gpt-3.5-turbo #??
#  retries: 10 #??????5
#  session-expiration-time: 30 #????????????
  base-url: https://api.dk666.cc/ #??????https://api.openai.com/???????/??

baidu:
  key: q0a1kmQPtgPw6xeiH72gruw17K4QGT3i
  region: 450124

server:
  port: 8080